// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9gum0LZTLi_YzUAFXpUDPnCxUBicBo9s',
    appId: '1:942397338758:web:928cdc3e0cdbaf8f0a4d07',
    messagingSenderId: '942397338758',
    projectId: 'livelocation-65082',
    authDomain: 'livelocation-65082.firebaseapp.com',
    databaseURL: 'https://livelocation-65082-default-rtdb.firebaseio.com',
    storageBucket: 'livelocation-65082.appspot.com',
    measurementId: 'G-SV9V54TREW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBecRntxe_SJYzpx6hddd72-SFtTLB9Rzc',
    appId: '1:942397338758:android:f658fe928d0fe6e80a4d07',
    messagingSenderId: '942397338758',
    projectId: 'livelocation-65082',
    databaseURL: 'https://livelocation-65082-default-rtdb.firebaseio.com',
    storageBucket: 'livelocation-65082.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGOVUTqGKQiyp5TzEZRRjB6dhTvqBAAVM',
    appId: '1:942397338758:ios:937920680e29c58b0a4d07',
    messagingSenderId: '942397338758',
    projectId: 'livelocation-65082',
    databaseURL: 'https://livelocation-65082-default-rtdb.firebaseio.com',
    storageBucket: 'livelocation-65082.appspot.com',
    iosBundleId: 'com.example.liveLocation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGOVUTqGKQiyp5TzEZRRjB6dhTvqBAAVM',
    appId: '1:942397338758:ios:937920680e29c58b0a4d07',
    messagingSenderId: '942397338758',
    projectId: 'livelocation-65082',
    databaseURL: 'https://livelocation-65082-default-rtdb.firebaseio.com',
    storageBucket: 'livelocation-65082.appspot.com',
    iosBundleId: 'com.example.liveLocation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9gum0LZTLi_YzUAFXpUDPnCxUBicBo9s',
    appId: '1:942397338758:web:6dfdea2c0cb4de990a4d07',
    messagingSenderId: '942397338758',
    projectId: 'livelocation-65082',
    authDomain: 'livelocation-65082.firebaseapp.com',
    databaseURL: 'https://livelocation-65082-default-rtdb.firebaseio.com',
    storageBucket: 'livelocation-65082.appspot.com',
    measurementId: 'G-BVDXMRC5P1',
  );
}
